[alias]
cd = "check"
bd = "build"
td = "llvm-cov"
rd = "run"
dd = "doc --no-deps --document-private-items"

cr = "check --release"
br = "build --release"
tr = "llvm-cov --release"
rr = "run --release"
dr = "doc --no-deps --document-private-items --release"

cl = "clean"

[env]
ENV_FLAG = "flag"
